### ISSUE TITLE
Nothing works on Paper 1.21.4

### ISSUE THREAD

**Issue by Ajneb97** [toxicity188/BetterHud#300]
1. Tell me the detail about your problem.
When using BetterHud on Paper 1.21.4, nothing works, the console spams multiple errors when starting or reloading the plugin.

2. Upload some screenshot or text log related your issue. such as:
```
[09:44:52 INFO]: [BetterHud] Reloading HUD...
[09:44:52 INFO]:  [!] Unable to load this hud: test_hud in default-hud.yml
[09:44:52 INFO]:  [!] Reason: 'net.kyori.adventure.text.format.StyleSetter net.kyori.adventure.text.TextComponent$Builder.shadowColor(net.kyori.adventure.util.ARGBLike)'
[09:44:52 INFO]:  [!] Stack trace:
[09:44:52 INFO]:  [!] java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.StyleSetter net.kyori.adventure.text.TextComponent$Builder.shadowColor(net.kyori.adventure.util.ARGBLike)'
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.AdventuresKt.shadow(Adventures.kt:223)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.AdventuresKt.shadow(Adventures.kt:219)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.image.ImageComponent.apply(ImageComponent.kt:38)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.renderer.ImageRenderer.<init>(ImageRenderer.kt:21)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.hud.HudImageParser.<init>(HudImageParser.kt:70)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.hud.HudParser.<init>(HudParser.kt:22)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.hud.HudImpl.elements$lambda$1(HudImpl.kt:59)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.mapSubConfiguration(Files.kt:41)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.hud.HudImpl.<init>(HudImpl.kt:45)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload$lambda$0$0$0(HudManagerImpl.kt:33)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.MapsKt.putSync(Maps.kt:10)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload$lambda$0(HudManagerImpl.kt:32)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.YamlsKt.forEachAllYaml$lambda$0(Yamls.kt:71)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:30)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder$lambda$0(Files.kt:29)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEach(Files.kt:48)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:28)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.YamlsKt.forEachAllYaml(Yamls.kt:66)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.HudManagerImpl.reload(HudManagerImpl.kt:30)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.BetterHudImpl.reload(BetterHudImpl.kt:120)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.api.BetterHud.reload(BetterHud.java:76)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.CommandManager$module$1.reload$lambda$0(CommandManager.kt:142)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.PluginsKt.asyncTask$lambda$0(Plugins.kt:40)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[09:44:52 INFO]: [BetterHud] Reloading Popup...
[09:44:52 INFO]:  [!] Unable to load this popup: entity_health_popup in entity-popup.yml
[09:44:52 INFO]:  [!] Reason: 'net.kyori.adventure.text.format.StyleSetter net.kyori.adventure.text.TextComponent$Builder.shadowColor(net.kyori.adventure.util.ARGBLike)'
[09:44:52 INFO]:  [!] Stack trace:
[09:44:52 INFO]:  [!] java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.StyleSetter net.kyori.adventure.text.TextComponent$Builder.shadowColor(net.kyori.adventure.util.ARGBLike)'
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.AdventuresKt.shadow(Adventures.kt:223)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.AdventuresKt.shadow(Adventures.kt:219)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.image.ImageComponent.apply(ImageComponent.kt:38)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.renderer.ImageRenderer.<init>(ImageRenderer.kt:21)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.popup.PopupLayout$PopupElement.<init>(PopupLayout.kt:153)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.popup.PopupLayout$PopupLayoutGroup.<init>(PopupLayout.kt:66)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.popup.PopupLayout.<init>(PopupLayout.kt:45)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.popup.PopupImpl.layouts$lambda$0$1(PopupImpl.kt:85)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.mapSubConfiguration(Files.kt:41)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.popup.PopupImpl.<init>(PopupImpl.kt:79)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.PopupManagerImpl.reload$lambda$0$0$0(PopupManagerImpl.kt:30)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.MapsKt.putSync(Maps.kt:10)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.PopupManagerImpl.reload$lambda$0(PopupManagerImpl.kt:29)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.YamlsKt.forEachAllYaml$lambda$0(Yamls.kt:71)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:30)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder$lambda$0(Files.kt:29)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEach(Files.kt:48)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.FilesKt.forEachAllFolder(Files.kt:28)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.YamlsKt.forEachAllYaml(Yamls.kt:66)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.PopupManagerImpl.reload(PopupManagerImpl.kt:27)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.BetterHudImpl.reload(BetterHudImpl.kt:120)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.api.BetterHud.reload(BetterHud.java:76)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.manager.CommandManager$module$1.reload$lambda$0(CommandManager.kt:142)
        at BetterHud-bukkit-1.14.0.jar//kr.toxicity.hud.util.PluginsKt.asyncTask$lambda$0(Plugins.kt:40)
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78)
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

3. Remember to notice your environment
- Windows 11, Paper 1.21.4
