### ISSUE TITLE
BetterHud 2.1.0-SNAPSHOT-446 fails to enable on Purpur 26.2 due to Adventure NoSuchMethodErrorAny issue

### ISSUE THREAD

**Issue by Yaroslav-mc** [toxicity188/BetterHud#454]
1. Problem details
BetterHud 2.1.0-SNAPSHOT-446 fails to enable on my Purpur 26.2 server.
The plugin starts loading, but crashes during initialization and then disables itself. It looks related to Adventure API compatibility, because the root error is:

java.lang.NoSuchMethodError: 'net.kyori.adventure.text.BuildableComponent net.kyori.adventure.text.TextComponent$Builder.build()'

This happens before any HUD config can be used, so I do not think this is caused by my HUD yml configuration.

2. Error log
[17:17:01 INFO]: [BetterHud] Enabling BetterHud v2.1.0-SNAPSHOT-446
[17:17:01 ERROR]: Error occurred while enabling BetterHud v2.1.0-SNAPSHOT-446 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class kr.toxicity.hud.manager.CommandManager
        at BetterHud-bukkit-2.1.0-SNAPSHOT-446.jar//kr.toxicity.hud.bootstrap.bukkit.BukkitBootstrapImpl.onEnable(BukkitBootstrapImpl.kt:210) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-26.2.build.2603-experimental.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:201) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-26.2.build.2603-experimental.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:651) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:386) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'net.kyori.adventure.text.BuildableComponent net.kyori.adventure.text.TextComponent$Builder.build()' [in thread "Server thread"]
        at BetterHud-bukkit-2.1.0-SNAPSHOT-446.jar//kr.toxicity.hud.shaded.kr.toxicity.command.impl.CommandPrefix.<clinit>(CommandPrefix.java:44) ~[?:?]
        at BetterHud-bukkit-2.1.0-SNAPSHOT-446.jar//kr.toxicity.hud.shaded.kr.toxicity.command.impl.BetterCommand.<init>(BetterCommand.java:48) ~[?:?]
        at BetterHud-bukkit-2.1.0-SNAPSHOT-446.jar//kr.toxicity.hud.manager.CommandManager.<clinit>(CommandManager.kt:33) ~[?:?]
        at BetterHud-bukkit-2.1.0-SNAPSHOT-446.jar//kr.toxicity.hud.bootstrap.bukkit.BukkitBootstrapImpl.onLoad(BukkitBootstrapImpl.kt:204) ~[?:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:39) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:563) ~[purpur-26.2.jar:26.2-2603-391dda3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:340) ~[purpur-26.2.jar:26.2-2603-391dda3]
        ... 3 more

3. Environment
OS: Windows 11
Java version: Java 25
Server platform: Purpur
Server version: 26.2
Purpur build: 2603
Minecraft version: 26.2
BetterHud version: 2.1.0-SNAPSHOT-446
BetterHud file: BetterHud-bukkit-2.1.0-SNAPSHOT-446.jar
Platform jar downloaded: Bukkit / Paper / Purpur version from Modrinth

This is not a hybrid server such as ArcLight.
This is not related to Optifine or ItemsAdder.
This is a dedicated server-side plugin issue.

4. Expected behavior
BetterHud should enable normally on Purpur 26.2.

5. Actual behavior
BetterHud fails during startup with NoClassDefFoundError / NoSuchMethodError and gets disabled automatically.

6. Additional note
The Modrinth version page lists BetterHud 2.1.0-SNAPSHOT-446 as compatible with Minecraft 26.2 and Bukkit/Paper/Purpur, so I expected it to work on Purpur 26.2.

**Comment by toxicity188** [comment]
unproducable; update your Purpur to use Adventure 5.2.0
